# Generated by Django 2.2.1 on 2019-06-18 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Joining_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
