# Generated by Django 2.2.1 on 2019-06-19 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20190618_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Joining_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
