# Generated by Django 2.2.1 on 2019-06-19 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_auto_20190619_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
