# Generated by Django 2.2.1 on 2019-06-19 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_auto_20190619_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Joining_date',
            field=models.DateField(default=datetime.date(2019, 6, 19)),
        ),
    ]
