# Generated by Django 2.2.1 on 2019-06-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_auto_20190619_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(blank=True, upload_to='media/profile_pic/'),
        ),
    ]
