# Generated by Django 2.2.1 on 2019-06-21 05:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0011_auto_20190620_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Joining_date',
            field=models.DateField(default=datetime.date(2019, 6, 21)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
